### ISSUE TITLE
rearm vehicles with agm interaction

### ISSUE THREAD

**Issue by kripto202** [KoffeinFlummi/AGM#2042] opened 2015-01-28 17:26 UTC
Since we have repair and refuel, might as well add a rearm function to the agm interaction. I always seem to have a hard time rearming via scroll menu if the truck is right next to me.

**Comment by commy2** [comment] 2015-01-30 12:04
Duplicate of https://github.com/KoffeinFlummi/AGM/issues/1923

**Closed by commy2** 2015-01-30 12:04 UTC
Labels: duplicate, feature request
