### ISSUE TITLE
Strange rhs humvee behavior when it takes damage.

### ISSUE THREAD

**Issue by Tachii** [KoffeinFlummi/AGM#1909] opened 2015-01-04 17:14 UTC
How to reproduce:

Place rhs m2 humvee and destroy all the wheels.
Shoot the humvee with m136 and watch the wheels appearing on the vehicle again. 

Basically it looks like you can't destroy rhs humvee if you are using rhs + agm

Only happens with agm

**Comment by commy2** [comment] 2015-01-04 18:26
Duplicate of https://github.com/KoffeinFlummi/AGM/issues/1816

**Closed by commy2** 2015-01-04 18:26 UTC
Labels: bug, duplicate

**Comment by Tachii** [comment] 2015-01-04 20:21
It's not only that they are unkillable, it's also that the wheels are regenerating :)

**Comment by commy2** [comment] 2015-01-04 22:34
It's the same bug that causes both.

**Comment by Tachii** [comment] 2015-01-08 15:26
Some video http://youtu.be/eza94cbYG-Y

**Comment by esteldunedain** [comment] 2015-01-08 16:42
> Some video http://youtu.be/eza94cbYG-Y

lol, Repair gun?
