### ISSUE TITLE
Chain detonation

### ISSUE THREAD

**Issue by LokstarValHallen** [KoffeinFlummi/AGM#1985] opened 2015-01-21 02:49 UTC
I remember, that in ArmA 2 it was possible to set off multiple charges just by detonating one. It would be nice to have such behaviour in ArmA 3.

**Comment by Tachii** [comment] 2015-01-21 02:57
Related: https://github.com/KoffeinFlummi/AGM/issues/1661

**Comment by bux578** [comment] 2015-01-21 07:46
duplicate of #709

**Closed by bux578** 2015-01-21 07:46 UTC
