### ISSUE TITLE
Artillery Computer  

### ISSUE THREAD

**Issue by xPride** [KoffeinFlummi/AGM#2010] opened 2015-01-25 11:28 UTC
Hi guys, look at http://www.armaholic.com/page.php?id=27995 - very good realization of ArtComp.
If the author agrees - this is a very welcome part of your project.

**Comment by Trigger81** [comment] 2015-01-25 11:41
look at https://github.com/KoffeinFlummi/AGM/issues/1194

**Comment by commy2** [comment] 2015-01-25 12:20
: )

Duplicate of https://github.com/KoffeinFlummi/AGM/issues/1194

**Closed by commy2** 2015-01-25 12:20 UTC
Labels: duplicate
