### ISSUE TITLE
AI fastroping, ordering fastrope as pilot

### ISSUE THREAD

**Issue by taro8** [KoffeinFlummi/AGM#2188] opened 2015-03-18 12:59 UTC
When player uses fastrope action then every AI in his squad (maybe team only?) should fastrope along with him without need to give an order. Or, give AI normal action (to fastrope) that is invisible to player, but can be chosen when ordering AI to use action ( I think it was 6 on keyboard).

When player is a pilot then his fastrope action should be replaced with an action that makes every AI in cargo fastrope instead. Its kind of retarded to give pilot option to fastrope as the helo will just fall on top of him if he does so.

**Comment by commy2** [comment] 2015-03-18 17:08
Duplicate of https://github.com/KoffeinFlummi/AGM/issues/2121

**Closed by commy2** 2015-03-18 17:08 UTC
Labels: duplicate, feature request

**Comment by taro8** [comment] 2015-03-19 10:44
This is NOT a duplicate. Right now there is NO way to order AI to fastrope, this is what I was asking for, the previous issue was about ordering players to fastrope when you are the pilot. Again Im talking about AI.
