### ISSUE TITLE
Add a Spectator CAMERA for Unconscious player

### ISSUE THREAD

**Issue by ChristopheTdn** [KoffeinFlummi/AGM#2058] opened 2015-02-02 14:52 UTC
A feature request

In Coop game, a spectator camera, lock on player or team player must be a must have to maintain the interest on a game for a unconscious player. instead of the black screen... 

Some feature like TF RADIO OFF or ON or the ever present CHAT ON/OFF will be

Keep the good work

**Comment by kripto202** [comment] 2015-02-02 15:27
i wouldn't recommend this unless it would be set through a module but yet spectator camera are pretty buggy sometimes

**Comment by KoffeinFlummi** [comment] 2015-02-03 10:59
Duplicate of #1099.

**Closed by KoffeinFlummi** 2015-02-03 10:59 UTC

**Comment by ChristopheTdn** [comment] 2015-02-03 13:38
There s a difference with #1099 i Think.

 I expected a Extrernal camera for COOP Mod Only, focus on the player or templayer for maintain interest for the UNCONSCIOUS STATE.

No Free camera, activable by module or command.  Camera for DEAD STATE ever exist in other MODS and works like a CHARM but are incompatible with the unconscious state. 

Thanks for your interest

**Comment by esteldunedain** [comment] 2015-02-03 13:41
I think what @KoffeinFlummi meant is that, like stated on #1099, we are not interested in programming a spectator mode at the moment. We could consider it if somebody donates one though.

**Comment by BaerMitUmlaut** [comment] 2015-02-04 10:29
>We could consider it if somebody donates one though.

https://github.com/BaerMitUmlaut/A3G-SpectatorCam
Could absolutely make this configurable via modules etc. If you're interested, let me know, and I can work on converting it a bit to make it more suitable for AGM.
That said, I don't like the idea of being able to spectate while unconscious at all. It allows metagaming and I'm really not a fan of that. It's GPL though so do whatever you want with it.
