### ISSUE TITLE
Problem with medical system (Bandage)

### ISSUE THREAD

**Issue by mrkrikajs** [KoffeinFlummi/AGM#1907] opened 2015-01-04 14:28 UTC
Hello, I have a problem with bandaging via AGM. I am using AGM on Playwithsix and if I use bandage on my body with several  injuries... i am complet. allright. One bandage heals entire body, but I didnt choose "Single Bandage" in AGM options. I tried everything (remove other mods, change settings in AMG aso..) Please help.

**Comment by jonpas** [comment] 2015-01-04 15:30
>but I choosed "Single Bandage" in AGM options

That means that one bandage will bandage the whole body...

**Comment by mrkrikajs** [comment] 2015-01-04 15:56
Yeah yeah... my fold, I fixed my messag., soo? I didnt choose "Single Bandage" but one bandage still heals entire body.

**Comment by commy2** [comment] 2015-01-04 16:06
Duplicate of https://github.com/KoffeinFlummi/AGM/issues/1855

**Closed by commy2** 2015-01-04 16:06 UTC
Labels: bug, duplicate

**Comment by mrkrikajs** [comment] 2015-01-04 16:49
Oh, thx you sir. Soo.. it will be fixed?

**Comment by jonpas** [comment] 2015-01-04 16:51
Yes, in 0.95.1.

**Comment by mrkrikajs** [comment] 2015-01-04 17:21
sorry but in 0.9.5.1 this problem still is :)

**Comment by PabstMirror** [comment] 2015-01-04 17:28
0.9.5.1 isn't out yet 
I think there was a hotfix on PWS because a wrong file got uploaded, but we're still only on 0.9.5
https://github.com/KoffeinFlummi/AGM/releases

**Comment by esteldunedain** [comment] 2015-01-04 18:56
@mrkrikajs, the issue is not fixed yet, but it will be when 0.9.5.1 is released.

**Comment by bux578** [comment] 2015-01-04 18:58
> when 0.9.5.1 is released.

0.95.1

**Comment by esteldunedain** [comment] 2015-01-04 19:33
ok @mrkrikajs, it should be fixed now.

**Comment by mrkrikajs** [comment] 2015-01-09 18:22
@esteldunedain Nope, still not working. at least on Paywithsix.

**Comment by esteldunedain** [comment] 2015-01-09 18:24
> when 0.95.1 is released.

0.95.1 it's not released yet. PWS still has the 0.95 version
