### ISSUE TITLE
while carrying a person, do drop backpack of carrying person and carried person

### ISSUE THREAD

**Issue by kOepi123** [KoffeinFlummi/AGM#2149] opened 2015-03-03 17:15 UTC
Hey ho,

I would like to request a feature which would drop the backpacks of the carrying person and of the carried one, as it is very unrealistic to be able to carry a person in the firemans carry like with own 20 kg backpack and carried 20 kg backpack.

Of course an empty backpack would not be an issue regarding the weight, I wouldnt make differences with it though.
Let me know wether I can help you with anything 
( e.g. maximum weight both would have to be able to carry )

greetz

kOepi

**Comment by BaerMitUmlaut** [comment] 2015-03-03 17:30
Related/Duplicate: #1717

**Comment by kOepi123** [comment] 2015-03-03 18:11
mhm. I dont see a relation. I dont suggest to take away the weapon from anyone while carrying, yet.

**Comment by BaerMitUmlaut** [comment] 2015-03-03 18:24
Dropping somebodys backpack is related to the above issue.

**Comment by kOepi123** [comment] 2015-03-03 18:32
I dont see it in the starting thread itself.
does it connect the need to drop own and someones backpack in order to carry someone?

**Comment by commy2** [comment] 2015-03-06 20:25
It has the same techinical limitations. To not spam the issue tracker with unsolvable open issues, our policy is to close them as duplicate of #1717.
Once #1717 is solved all duplicates will be reviewed.

BI feature request:
http://feedback.arma3.com/view.php?id=22000

**Closed by commy2** 2015-03-06 20:25 UTC
