### ISSUE TITLE
Dont close explosives menu after detonating each explosive.

### ISSUE THREAD

**Issue by Ataraxic89** [KoffeinFlummi/AGM#2040] opened 2015-01-28 15:48 UTC
I dont know the realism here but its quite annoying to have to reopen the context menu and navigate to each explosive when you are trying to make them go off in quick succession. 

Perhaps we should also be able to ctrl-click explosives to add them to a group and detonate at the same time. Leaving this menu open means the player can easily decide how long to wait between bombs.

**Comment by kripto202** [comment] 2015-01-28 17:23
I don't remember but if you have the explosives menu up, can you still walk around and move if you need to?

**Comment by commy2** [comment] 2015-01-30 12:45
Duplicate of https://github.com/KoffeinFlummi/AGM/issues/709

**Closed by commy2** 2015-01-30 12:45 UTC
Labels: duplicate, feature request
