### ISSUE TITLE
Interaction with alive AI impossible

### ISSUE THREAD

**Issue by CfXIGer** [KoffeinFlummi/AGM#2053] opened 2015-01-31 22:38 UTC
I ran into the following problem:
When I'm hosting a server ingame, interacting with alive AI becomes impossible when another client is connected.
It works fine in editor and on listen server (that's what it's called, right?) as long as only I as the host am playing.
As soon as a friend as client is connected, the interaction menu only works on everything but alive AI. Dead AI works. Friend works. Vehicles etc. work.
This makes taking AI prisoners impossible.
This is using v0.95.1.

**Comment by PabstMirror** [comment] 2015-01-31 22:52
Does this happen everytime?

I couldn't reproduce in 0952 (https://github.com/KoffeinFlummi/AGM/releases/download/v0.95.2/AGM_v0.95.2.zip)

Could you post a RPT (%localappdata%/Arma 3/) from when it happened?

**Comment by commy2** [comment] 2015-01-31 23:01
Tried to repro it, but I couldn't do it.

A LAN Host
- can Interact with AI from group (AI-1) and another one not in the group (AI-2)
- connect with CLIENT B
- A can still interact with AI-1 & 2. Also with B
- B can Interact with AI1, 2 and A

**Comment by CfXIGer** [comment] 2015-01-31 23:32
RPT: http://pastebin.com/mfaAfarr

Could only test with 0952 later today, as my test buddy is not available right now.

Happened in two missions in the given RPT:
"[Co10]MilOpsM2B2_11(m)" and "[Co2]BreachTest"
Both are made by me, the first being a regular coop mission and the second one a small test thrown together from some flashbang-test to research this issue.

**Comment by commy2** [comment] 2015-02-01 09:25
- First of all, you should really think about what mods you are using. There are some serious `Updating base class` issues in the RPT file.
```
21:03:23 Updating base class ->BulletCore, by a3\weapons_f\config.bin/CfgAmmo/BulletBase/
21:03:23 Updating base class ->B_556x45_Ball, by a3\weapons_f\config.bin/CfgAmmo/B_556x45_Ball_Tracer_Red/
21:03:23 Updating base class ->B_762x51_Ball, by a3\weapons_f\config.bin/CfgAmmo/B_762x51_Tracer_Red/
```
`Updating base class` means that certain mods you use, change the class inheritance of classes from BI. That won't make much of difference when it's in UI elements only (BI does that themselves), but when such errors happen with `BulletCore` (== all rifle projectiles) something is seriously wrong. The error can cause uncertain config structure, where the config entries depend on loading order of the mods or plain wrong configs (those typical incompatibilites).

- I doubt that itself causes the incompatibilites. On the other hand there are a lot of those errors:
`21:33:29 Client: Object 2:678 (type Type_89) not found.`
which could be either causes by weird configs resulting from UBC, or your friend is using JSRS.

If he is using JSRS, then my advice is to not use it. If you really want, then make sure everyone is using it. The mod is neither local nor optional regardless if it's advertised as such.

- There is an errors in tags.sqf. Line 28. Depending on what tags.sqf does, it could maybe cause this? (Empty display created via `createDisplay` for example?).


Try to reproduce the issue. If you can, then make sure to test it again with only CBA and AGM enabled for all clients and the server.
Also make sure to right click the soldiers if you can't interact with them. Right-clicking "reveals" them, so your avatar even knows about them in the first place. Sounds weird, but thats how the Arma engine works.

**Comment by CfXIGer** [comment] 2015-02-01 10:02
Thanks for the information!

I will think about the base class updates, but (I'm not a pro at reading this thing, so bear with me) it seems it's the HLC-Mods and CUP that do this mainly. I have not noticed any particular problems with weapons, ammunition or ballistics (using AGM w/o wind/ballistics/scopes w/ AB here so that is an old story, works anyways). Will keep it in mind though.

JSRS is not used by either of us. I made a collection on PWS, shared and that's it. He should be using the same mods as I do, including the removal of some AGM-pbos.

tags.sqf is an outdated script that I was too lazy to update till now. It provides nametags with the display of the used gun on looking at an allied unit. I like it and it still works for the names (I know AGM has something similar, but I just like this one) yet the gun part is broken and only shows Binos or something instead of the actual guns. As this is only for allied units,  I don't think it's this. Also I can interact with allied players where this script should step into full effect and it happens with and without it.

When doing research on this yesterday, I already read something about the revealing thing. I will test this also, yet it does only happen under the named circumstances. I do not know about possible differences related with both, revealing for oneself and multiplayer with a client connected, but I will look into this.

I will try to reproduce the error with only CBA and (an updated version of) AGM later, hopefully. Will post results of the tests.

**Comment by commy2** [comment] 2015-02-01 10:45
`21:33:29 Client: Object 2:678 (type Type_89) not found.` means that the game tries to access a not-locally existing remote object. No idea why it happens here and if that has anything to d with this.

**Comment by CfXIGer** [comment] 2015-02-01 11:09
I am pretty sure they should be local to me, as I'm hosting the game on a non-dedi server. When alone, everything works. When my friend connect's as a client, it does not anymore.

**Comment by commy2** [comment] 2015-02-01 11:53
Spawned units (via `createUnit`) are not necessarily local to the server (depends on the locality of the group they are assigned to) and AIs in a group are transfered to the machine where the group leader is local.

**Comment by CfXIGer** [comment] 2015-02-01 12:18
All units have been placed in the editor. Also: It's probably not the MEC mod that causes it as in the first mission MEC-units were used while the second short test only used regular CSAT-units.

**Comment by CfXIGer** [comment] 2015-02-04 23:06
Okay, so I finally got around to do SOME testing. I used a simple VR-test-scenario with another buddy - and it worked instantly with all mods we used before enabled. Thus I presume it may have been a one-time-"something somewhere went terribly wrong"-bug or the problem lies with testbuddy no.1. I will report back if I can acquire further information on this in a few days.

**Comment by CfXIGer** [comment] 2015-02-06 21:27
Right, so I was able to test with buddy no.1 again with whom it bugged. We were actually not able to reproduce this time and it worked. I don't know what the hell went wrong last time but, because of some exams of his, further testing was not possible at the time, so sorry for troubeling you.

If this bug occurs again, I will report again but only after pinning it further down.

**Closed** 2015-02-07 11:14 UTC
Labels: bug, can't reproduce, need more info
