### ISSUE TITLE
AGM Spectatormode

### ISSUE THREAD

**Issue by Trigger81** [KoffeinFlummi/AGM#1919] opened 2015-01-06 11:15 UTC
Spectatormode with Support AGM- Medic- System, Name Tags, ACRE/ TFAR and so on like the Spectatormode in ArmA II ACE for example 

https://www.youtube.com/watch?v=BpG0ToakoGQ

**Comment by Tachii** [comment] 2015-01-06 13:31
Would be rly nice

**Comment by esteldunedain** [comment] 2015-01-06 13:34
Duplicate of https://github.com/KoffeinFlummi/AGM/issues/1099

Sorry guys, none of us is interested on programming this at the moment. There are already a couple of good alternatives out there. Of course, if anyone codes or donates one we will consider it for inclusion.

Cheers

**Closed by esteldunedain** 2015-01-06 13:34 UTC

**Comment by Trigger81** [comment] 2015-01-06 14:38
ohh sorry for duplicate .. shame on me
