### ISSUE TITLE
Lowering weapon

### ISSUE THREAD

**Issue by runnybunny** [KoffeinFlummi/AGM#2018] opened 2015-01-26 05:41 UTC
Since the latest release of agm my and my squad mates can not lower our weapons using the default 2xCntl button.

**Comment by PabstMirror** [comment] 2015-01-26 05:48
Dupe of #1992

Already fixed in dev: https://github.com/KoffeinFlummi/AGM/compare/v0.95.1...master

**Closed by PabstMirror** 2015-01-26 05:48 UTC
