### ISSUE TITLE
Separate unconsciousness wakeup enable/disable from AI and player

### ISSUE THREAD

**Issue by jj33** [KoffeinFlummi/AGM#2028] opened 2015-01-27 07:00 UTC
This is a feature request to allow the unconsciousness wake-up ability to be enabled or disabled independently for both the player and AI. Currently they are both enabled or disabled together.

This would allow coop mission designers to allow for the AI to just stay down and not wake up independently of the player wake-up feature.

**Comment by bux578** [comment] 2015-01-27 07:38
duplicate of #1904

**Closed by bux578** 2015-01-27 07:38 UTC
Labels: duplicate
