### ISSUE TITLE
Bleeding Bug

### ISSUE THREAD

**Issue by Abarth0** [KoffeinFlummi/AGM#2100] opened 2015-02-14 23:53 UTC
We've noticed that after an accident with a burning car some people were constantly bleeding. It hasn't solved with giving blood to these, they bleeded with no wounds. The medical menu said that they aren't bleeding.

**Comment by jonpas** [comment] 2015-02-15 00:50
Duplicate of #1978

**Closed** 2015-02-15 10:46 UTC
Labels: bug, duplicate
