### ISSUE TITLE
Second Primary Weapon

### ISSUE THREAD

**Issue by sagjangi** [KoffeinFlummi/AGM#2015] opened 2015-01-26 00:18 UTC
The ability to put a second rifle-type weapon in the launcher slot. I'm not necessarily a fan of this but I know several people wan't to see something like this. 

A compromise might be making it so that you cannot carry a backpack if you have a second primary weapon and /or you cannot switch between primary weapons on the fly (i.e. you have to switch them via the inventory menu).

**Comment by esteldunedain** [comment] 2015-01-26 00:22
Duplicate of https://github.com/KoffeinFlummi/AGM/issues/1886

**Closed by esteldunedain** 2015-01-26 00:22 UTC
