### ISSUE TITLE
Explosives detonation menu

### ISSUE THREAD

**Issue by LokstarValHallen** [KoffeinFlummi/AGM#1984] opened 2015-01-21 02:48 UTC
It would be nice if the explosives detonation menu remain open after detonating. It would be much more convenient if detonating multiple charges.

**Comment by Blackswater** [comment] 2015-01-21 17:44
or maybe mark multiply charges at the same time

**Comment by jonpas** [comment] 2015-01-21 18:04
This would be a nice feature until chain/multiple discharges.

**Comment by commy2** [comment] 2015-01-30 12:45
Duplicate of https://github.com/KoffeinFlummi/AGM/issues/709

**Closed by commy2** 2015-01-30 12:45 UTC
Labels: duplicate, feature request
