### ISSUE TITLE
Some helicopters are broken with latest patch

### ISSUE THREAD

**Issue by jayjay213** [KoffeinFlummi/AGM#2151] opened 2015-03-03 22:14 UTC
AGM Issue with latest update 1.40. The Huron is broken, its invisible. I think there are generally some issues with the helicopters and AGM after the last patch, i think. I get lots of errors when using the helicopters in the editor when AGM is active. Everything releated to the helicopters work, when i start arma without AGM.

**Comment by esteldunedain** [comment] 2015-03-03 22:47
Mmm; I think this might indicate BIS changed the inheritance chain of helicopters; unfortunately this probably means we have to change the class definitions in AGM to match the new layout. Until we manage to fix this, you could try removing AGM pbos gradually until you find out which one is causing the issue. The most likely candidates are:
- AGM_Aircraft
- AGM_FastRoping
- AGM_FireControlSystem
- AGM_Logistics

**Comment by jonpas** [comment] 2015-03-03 22:55
Some RPT errors, same thing happening to us but I currently don't have time to test without AGM. What's surprising is that on our main server all works fine (or so it looks like so far), while on our second, which has exact same server config, mods and even missions, the following RPT errors come up:
```
14:24:24 Error: bin\config.bin/CfgVehicles/I_Heli_light_03_base_F/Turrets/MainTurret/: Turret body mainTurret not found while initializing the model bmp.p3d
14:24:24 Error: bin\config.bin/CfgVehicles/I_Heli_light_03_base_F/Turrets/MainTurret/: Turret gun mainGun not found while initializing the model bmp.p3d
14:24:24 Error: bin\config.bin/CfgVehicles/I_Heli_light_03_F/Turrets/MainTurret/: Turret body mainTurret not found while initializing the model bmp.p3d
14:24:24 Error: bin\config.bin/CfgVehicles/I_Heli_light_03_F/Turrets/MainTurret/: Turret gun mainGun not found while initializing the model bmp.p3d
```

**Comment by esteldunedain** [comment] 2015-03-03 22:57
> What's surprising is that on our main server all works fine (or so it looks like so far), while on our second, which has exact same server config, mods and even missions, the following RPT errors come up

Maybe BIS changed/add a new patch name, that we it's therefore not in the requiredAddons of AGM_Core. If that's the case, then addon loading order could make a difference

**Comment by AlexanderViand** [comment] 2015-03-03 23:01
Test scenario: Place down Wildcat (unarmed) in editor, preview.
Vanilla: Works. @AGM: "Cannot open object "bmp.p3d""

Test scenario: Place down Wildcat (armed) in editor, preview:
Vanilla: Works. @AGM: arma3.exe has stopped working.

Reproduced several times.

**Comment by ImperialAlex** [comment] 2015-03-03 23:01
Test scenario: Place down Wildcat (unarmed) in editor, preview.
Vanilla: Works. @AGM: "Cannot open object "bmp.p3d""

Test scenario: Place down Wildcat (armed) in editor, preview:
Vanilla: Works. @AGM: arma3.exe has stopped working.

Reproduced several times.

**Comment by jonpas** [comment] 2015-03-03 23:06
> Maybe BIS changed/add a new patch name, that we it's therefore not in the requiredAddons of AGM_Core. If that's the case, then addon loading order could make a difference

And they don't even bother to say it in changelog... why am I not surprised?

I can do some further testing on both of our server boxes tomorrow, but don't have much time. First thing will be moving around mod loading order, then Vanilla only tests, see if it's AGM's fault or not (that's priority probably).

**Comment by FadiCBB** [comment] 2015-03-04 02:18
It's not a problem in vanilla.

**Comment by PabstMirror** [comment] 2015-03-04 02:59
Should be fixed in 846838139ba3bfe98827970ce3da82532d7587b9

**Comment by BlenderRUS** [comment] 2015-03-04 03:27
PabstMirror:
Error in agm_aircraft\config.cpp line 1042: defining existing class
  class Heli_light_03_unarmed_base_F: Heli_light_03_base_F {};
  class Heli_light_03_unarmed_base_F: Heli_light_03_unarmed_base_F {
    class MFD {};
  };

**Comment by PabstMirror** [comment] 2015-03-04 03:44
@BlenderRUS - many thanks, I guess I wasn't getting compile errors and assumed I had it right

**Comment by jonpas** [comment] 2015-03-04 05:58
> I guess I wasn't getting compile errors and assumed I had it right

For some reason Addon Builder doesn't check for double class definitions, Eliteness is a good tool for config verifications.

Does this justify a hotfix? (Want to know to know if it's worth fixing it on our side as well manually.)

**Comment by J4gz3ro** [comment] 2015-03-04 11:53
Until there is a fix for this issue, would it be possible to simply remove the affected modules from the server / clients without causing a complete mess?

The Lynx is our main workhorse in the air and letting go of AGM enitrely for a few sessions is not an option ;)

**Comment by BryanBoru** [comment] 2015-03-04 13:17
I was able to temporarily fix my server by using this fix http://forums.bistudio.com/showthread.php?189428-A3-Dedi-server-patch-1-40-Hotfix
plan on a semi-stress test later today to see how our AGM based mods work in mission

**Comment by armyinf0703** [comment] 2015-03-04 13:37
I found the issue with the ch-47 huron is tied to AGM- Realisticnames

**Comment by BryanBoru** [comment] 2015-03-04 14:31
So it's known, my server had the issue of crashing upon mission request to the client due to bad animation files and we do not use AGMrealisticnamesPBO, The fix linked here https://github.com/KoffeinFlummi/AGM/issues/2151#issuecomment-77155521 fixed the crash. Stress and AGM compatibility yet to be tested

**Comment by RFAKeen** [comment] 2015-03-04 16:42
This is a list of AGM pbo's that I needed to remove to get the Huron and the Armed version of the Wildcat to work. You also need to remove Kimi's HMD mod.

@Helo_HMDs_Kimi
agm_fastroping
agm_firecontrolsystem
agm_gforces
agm_realisticnames
agm_aircraft

**Comment by killaway** [comment] 2015-03-05 12:21
Hi, im having this problem now but im pretty new to arma. Could someone help me out please? 

Flight671@hotmail.com

**Closed** 2015-03-08 08:57 UTC
Labels: bug
